# Generated by Django 2.1.7 on 2019-03-29 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_assignment_content'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentdone',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teacher.Subject'),
            preserve_default=False,
        ),
    ]
