# Generated by Django 2.1.7 on 2019-03-30 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_assignmentdone_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentdone',
            name='assignment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='teacher.Assignment'),
        ),
    ]
