# Generated by Django 2.1.7 on 2019-03-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_assignment_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
